// File generated from our OpenAPI spec by Stainless.

package com.moderntreasury.api.models

import com.moderntreasury.api.models.*
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class BulkRequestCreateParamsTest {

    @Test
    fun createBulkRequestCreateParams() {
        BulkRequestCreateParams.builder()
            .actionType(BulkRequestCreateParams.ActionType.CREATE)
            .resourceType(BulkRequestCreateParams.ResourceType.PAYMENT_ORDER)
            .resources(
                listOf(
                    BulkRequestCreateParams.Resource.ofPaymentOrderAsyncCreateRequest(
                        BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest.builder()
                            .amount(123L)
                            .direction(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .Direction
                                    .CREDIT
                            )
                            .originatingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .type(PaymentOrderType.ACH)
                            .accounting(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .Accounting
                                    .builder()
                                    .accountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .classId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .accountingCategoryId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .accountingLedgerClassId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .chargeBearer(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .ChargeBearer
                                    .SHARED
                            )
                            .currency(Currency.AED)
                            .description("string")
                            .effectiveDate(LocalDate.parse("2019-12-27"))
                            .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .fallbackType(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .FallbackType
                                    .ACH
                            )
                            .foreignExchangeContract("string")
                            .foreignExchangeIndicator(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .ForeignExchangeIndicator
                                    .FIXED_TO_VARIABLE
                            )
                            .ledgerTransaction(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .LedgerTransactionCreateRequest
                                    .builder()
                                    .ledgerEntries(
                                        listOf(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .LedgerTransactionCreateRequest
                                                .LedgerEntryCreateRequest
                                                .builder()
                                                .amount(123L)
                                                .direction(TransactionDirection.CREDIT)
                                                .ledgerAccountId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .availableBalanceAmount(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .LedgerTransactionCreateRequest
                                                        .LedgerEntryCreateRequest
                                                        .AvailableBalanceAmount
                                                        .builder()
                                                        .build()
                                                )
                                                .lockVersion(123L)
                                                .metadata(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .LedgerTransactionCreateRequest
                                                        .LedgerEntryCreateRequest
                                                        .Metadata
                                                        .builder()
                                                        .build()
                                                )
                                                .pendingBalanceAmount(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .LedgerTransactionCreateRequest
                                                        .LedgerEntryCreateRequest
                                                        .PendingBalanceAmount
                                                        .builder()
                                                        .build()
                                                )
                                                .postedBalanceAmount(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .LedgerTransactionCreateRequest
                                                        .LedgerEntryCreateRequest
                                                        .PostedBalanceAmount
                                                        .builder()
                                                        .build()
                                                )
                                                .showResultingLedgerAccountBalances(true)
                                                .build()
                                        )
                                    )
                                    .description("string")
                                    .effectiveAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .effectiveDate(LocalDate.parse("2019-12-27"))
                                    .externalId("string")
                                    .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .ledgerableType(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .LedgerTransactionCreateRequest
                                            .LedgerableType
                                            .COUNTERPARTY
                                    )
                                    .metadata(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .LedgerTransactionCreateRequest
                                            .Metadata
                                            .builder()
                                            .build()
                                    )
                                    .status(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .LedgerTransactionCreateRequest
                                            .Status
                                            .ARCHIVED
                                    )
                                    .build()
                            )
                            .ledgerTransactionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .lineItems(
                                listOf(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .LineItemRequest
                                        .builder()
                                        .amount(123L)
                                        .accountingCategoryId("string")
                                        .description("string")
                                        .metadata(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .LineItemRequest
                                                .Metadata
                                                .builder()
                                                .build()
                                        )
                                        .build()
                                )
                            )
                            .metadata(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .Metadata
                                    .builder()
                                    .build()
                            )
                            .nsfProtected(true)
                            .originatingPartyName("string")
                            .priority(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .Priority
                                    .HIGH
                            )
                            .purpose("string")
                            .receivingAccount(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .ReceivingAccount
                                    .builder()
                                    .accountDetails(
                                        listOf(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .ReceivingAccount
                                                .AccountDetail
                                                .builder()
                                                .accountNumber("string")
                                                .accountNumberType(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .ReceivingAccount
                                                        .AccountDetail
                                                        .AccountNumberType
                                                        .IBAN
                                                )
                                                .build()
                                        )
                                    )
                                    .accountType(ExternalAccountType.CASH)
                                    .contactDetails(
                                        listOf(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .ReceivingAccount
                                                .ContactDetailCreateRequest
                                                .builder()
                                                .contactIdentifier("string")
                                                .contactIdentifierType(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .ReceivingAccount
                                                        .ContactDetailCreateRequest
                                                        .ContactIdentifierType
                                                        .EMAIL
                                                )
                                                .build()
                                        )
                                    )
                                    .ledgerAccount(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .ReceivingAccount
                                            .LedgerAccountCreateRequest
                                            .builder()
                                            .currency("string")
                                            .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("string")
                                            .normalBalance(TransactionDirection.CREDIT)
                                            .currencyExponent(123L)
                                            .description("string")
                                            .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .ledgerableType(
                                                BulkRequestCreateParams.Resource
                                                    .PaymentOrderAsyncCreateRequest
                                                    .ReceivingAccount
                                                    .LedgerAccountCreateRequest
                                                    .LedgerableType
                                                    .EXTERNAL_ACCOUNT
                                            )
                                            .metadata(
                                                BulkRequestCreateParams.Resource
                                                    .PaymentOrderAsyncCreateRequest
                                                    .ReceivingAccount
                                                    .LedgerAccountCreateRequest
                                                    .Metadata
                                                    .builder()
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .metadata(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .ReceivingAccount
                                            .Metadata
                                            .builder()
                                            .build()
                                    )
                                    .name("string")
                                    .partyAddress(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .ReceivingAccount
                                            .AddressRequest
                                            .builder()
                                            .country("string")
                                            .line1("string")
                                            .line2("string")
                                            .locality("string")
                                            .postalCode("string")
                                            .region("string")
                                            .build()
                                    )
                                    .partyIdentifier("string")
                                    .partyName("string")
                                    .partyType(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .ReceivingAccount
                                            .PartyType
                                            .BUSINESS
                                    )
                                    .plaidProcessorToken("string")
                                    .routingDetails(
                                        listOf(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .ReceivingAccount
                                                .RoutingDetail
                                                .builder()
                                                .routingNumber("string")
                                                .routingNumberType(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .ReceivingAccount
                                                        .RoutingDetail
                                                        .RoutingNumberType
                                                        .ABA
                                                )
                                                .paymentType(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .ReceivingAccount
                                                        .RoutingDetail
                                                        .PaymentType
                                                        .ACH
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .receivingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .remittanceInformation("string")
                            .sendRemittanceAdvice(true)
                            .statementDescriptor("string")
                            .subtype(PaymentOrderSubtype.BACS_NEW_INSTRUCTION)
                            .transactionMonitoringEnabled(true)
                            .ultimateOriginatingPartyIdentifier("string")
                            .ultimateOriginatingPartyName("string")
                            .ultimateReceivingPartyIdentifier("string")
                            .ultimateReceivingPartyName("string")
                            .build()
                    )
                )
            )
            .metadata(BulkRequestCreateParams.Metadata.builder().build())
            .build()
    }

    @Test
    fun getBody() {
        val params =
            BulkRequestCreateParams.builder()
                .actionType(BulkRequestCreateParams.ActionType.CREATE)
                .resourceType(BulkRequestCreateParams.ResourceType.PAYMENT_ORDER)
                .resources(
                    listOf(
                        BulkRequestCreateParams.Resource.ofPaymentOrderAsyncCreateRequest(
                            BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                .builder()
                                .amount(123L)
                                .direction(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .Direction
                                        .CREDIT
                                )
                                .originatingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .type(PaymentOrderType.ACH)
                                .accounting(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .Accounting
                                        .builder()
                                        .accountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .classId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .accountingCategoryId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .accountingLedgerClassId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .chargeBearer(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .ChargeBearer
                                        .SHARED
                                )
                                .currency(Currency.AED)
                                .description("string")
                                .effectiveDate(LocalDate.parse("2019-12-27"))
                                .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .fallbackType(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .FallbackType
                                        .ACH
                                )
                                .foreignExchangeContract("string")
                                .foreignExchangeIndicator(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .ForeignExchangeIndicator
                                        .FIXED_TO_VARIABLE
                                )
                                .ledgerTransaction(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .LedgerTransactionCreateRequest
                                        .builder()
                                        .ledgerEntries(
                                            listOf(
                                                BulkRequestCreateParams.Resource
                                                    .PaymentOrderAsyncCreateRequest
                                                    .LedgerTransactionCreateRequest
                                                    .LedgerEntryCreateRequest
                                                    .builder()
                                                    .amount(123L)
                                                    .direction(TransactionDirection.CREDIT)
                                                    .ledgerAccountId(
                                                        "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                    )
                                                    .availableBalanceAmount(
                                                        BulkRequestCreateParams.Resource
                                                            .PaymentOrderAsyncCreateRequest
                                                            .LedgerTransactionCreateRequest
                                                            .LedgerEntryCreateRequest
                                                            .AvailableBalanceAmount
                                                            .builder()
                                                            .build()
                                                    )
                                                    .lockVersion(123L)
                                                    .metadata(
                                                        BulkRequestCreateParams.Resource
                                                            .PaymentOrderAsyncCreateRequest
                                                            .LedgerTransactionCreateRequest
                                                            .LedgerEntryCreateRequest
                                                            .Metadata
                                                            .builder()
                                                            .build()
                                                    )
                                                    .pendingBalanceAmount(
                                                        BulkRequestCreateParams.Resource
                                                            .PaymentOrderAsyncCreateRequest
                                                            .LedgerTransactionCreateRequest
                                                            .LedgerEntryCreateRequest
                                                            .PendingBalanceAmount
                                                            .builder()
                                                            .build()
                                                    )
                                                    .postedBalanceAmount(
                                                        BulkRequestCreateParams.Resource
                                                            .PaymentOrderAsyncCreateRequest
                                                            .LedgerTransactionCreateRequest
                                                            .LedgerEntryCreateRequest
                                                            .PostedBalanceAmount
                                                            .builder()
                                                            .build()
                                                    )
                                                    .showResultingLedgerAccountBalances(true)
                                                    .build()
                                            )
                                        )
                                        .description("string")
                                        .effectiveAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .effectiveDate(LocalDate.parse("2019-12-27"))
                                        .externalId("string")
                                        .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .ledgerableType(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .LedgerTransactionCreateRequest
                                                .LedgerableType
                                                .COUNTERPARTY
                                        )
                                        .metadata(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .LedgerTransactionCreateRequest
                                                .Metadata
                                                .builder()
                                                .build()
                                        )
                                        .status(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .LedgerTransactionCreateRequest
                                                .Status
                                                .ARCHIVED
                                        )
                                        .build()
                                )
                                .ledgerTransactionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .lineItems(
                                    listOf(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .LineItemRequest
                                            .builder()
                                            .amount(123L)
                                            .accountingCategoryId("string")
                                            .description("string")
                                            .metadata(
                                                BulkRequestCreateParams.Resource
                                                    .PaymentOrderAsyncCreateRequest
                                                    .LineItemRequest
                                                    .Metadata
                                                    .builder()
                                                    .build()
                                            )
                                            .build()
                                    )
                                )
                                .metadata(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .Metadata
                                        .builder()
                                        .build()
                                )
                                .nsfProtected(true)
                                .originatingPartyName("string")
                                .priority(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .Priority
                                        .HIGH
                                )
                                .purpose("string")
                                .receivingAccount(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .ReceivingAccount
                                        .builder()
                                        .accountDetails(
                                            listOf(
                                                BulkRequestCreateParams.Resource
                                                    .PaymentOrderAsyncCreateRequest
                                                    .ReceivingAccount
                                                    .AccountDetail
                                                    .builder()
                                                    .accountNumber("string")
                                                    .accountNumberType(
                                                        BulkRequestCreateParams.Resource
                                                            .PaymentOrderAsyncCreateRequest
                                                            .ReceivingAccount
                                                            .AccountDetail
                                                            .AccountNumberType
                                                            .IBAN
                                                    )
                                                    .build()
                                            )
                                        )
                                        .accountType(ExternalAccountType.CASH)
                                        .contactDetails(
                                            listOf(
                                                BulkRequestCreateParams.Resource
                                                    .PaymentOrderAsyncCreateRequest
                                                    .ReceivingAccount
                                                    .ContactDetailCreateRequest
                                                    .builder()
                                                    .contactIdentifier("string")
                                                    .contactIdentifierType(
                                                        BulkRequestCreateParams.Resource
                                                            .PaymentOrderAsyncCreateRequest
                                                            .ReceivingAccount
                                                            .ContactDetailCreateRequest
                                                            .ContactIdentifierType
                                                            .EMAIL
                                                    )
                                                    .build()
                                            )
                                        )
                                        .ledgerAccount(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .ReceivingAccount
                                                .LedgerAccountCreateRequest
                                                .builder()
                                                .currency("string")
                                                .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .name("string")
                                                .normalBalance(TransactionDirection.CREDIT)
                                                .currencyExponent(123L)
                                                .description("string")
                                                .ledgerableId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .ledgerableType(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .ReceivingAccount
                                                        .LedgerAccountCreateRequest
                                                        .LedgerableType
                                                        .EXTERNAL_ACCOUNT
                                                )
                                                .metadata(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .ReceivingAccount
                                                        .LedgerAccountCreateRequest
                                                        .Metadata
                                                        .builder()
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .metadata(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .ReceivingAccount
                                                .Metadata
                                                .builder()
                                                .build()
                                        )
                                        .name("string")
                                        .partyAddress(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .ReceivingAccount
                                                .AddressRequest
                                                .builder()
                                                .country("string")
                                                .line1("string")
                                                .line2("string")
                                                .locality("string")
                                                .postalCode("string")
                                                .region("string")
                                                .build()
                                        )
                                        .partyIdentifier("string")
                                        .partyName("string")
                                        .partyType(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .ReceivingAccount
                                                .PartyType
                                                .BUSINESS
                                        )
                                        .plaidProcessorToken("string")
                                        .routingDetails(
                                            listOf(
                                                BulkRequestCreateParams.Resource
                                                    .PaymentOrderAsyncCreateRequest
                                                    .ReceivingAccount
                                                    .RoutingDetail
                                                    .builder()
                                                    .routingNumber("string")
                                                    .routingNumberType(
                                                        BulkRequestCreateParams.Resource
                                                            .PaymentOrderAsyncCreateRequest
                                                            .ReceivingAccount
                                                            .RoutingDetail
                                                            .RoutingNumberType
                                                            .ABA
                                                    )
                                                    .paymentType(
                                                        BulkRequestCreateParams.Resource
                                                            .PaymentOrderAsyncCreateRequest
                                                            .ReceivingAccount
                                                            .RoutingDetail
                                                            .PaymentType
                                                            .ACH
                                                    )
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                                .receivingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .remittanceInformation("string")
                                .sendRemittanceAdvice(true)
                                .statementDescriptor("string")
                                .subtype(PaymentOrderSubtype.BACS_NEW_INSTRUCTION)
                                .transactionMonitoringEnabled(true)
                                .ultimateOriginatingPartyIdentifier("string")
                                .ultimateOriginatingPartyName("string")
                                .ultimateReceivingPartyIdentifier("string")
                                .ultimateReceivingPartyName("string")
                                .build()
                        )
                    )
                )
                .metadata(BulkRequestCreateParams.Metadata.builder().build())
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.actionType()).isEqualTo(BulkRequestCreateParams.ActionType.CREATE)
        assertThat(body.resourceType())
            .isEqualTo(BulkRequestCreateParams.ResourceType.PAYMENT_ORDER)
        assertThat(body.resources())
            .isEqualTo(
                listOf(
                    BulkRequestCreateParams.Resource.ofPaymentOrderAsyncCreateRequest(
                        BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest.builder()
                            .amount(123L)
                            .direction(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .Direction
                                    .CREDIT
                            )
                            .originatingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .type(PaymentOrderType.ACH)
                            .accounting(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .Accounting
                                    .builder()
                                    .accountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .classId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .accountingCategoryId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .accountingLedgerClassId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .chargeBearer(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .ChargeBearer
                                    .SHARED
                            )
                            .currency(Currency.AED)
                            .description("string")
                            .effectiveDate(LocalDate.parse("2019-12-27"))
                            .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .fallbackType(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .FallbackType
                                    .ACH
                            )
                            .foreignExchangeContract("string")
                            .foreignExchangeIndicator(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .ForeignExchangeIndicator
                                    .FIXED_TO_VARIABLE
                            )
                            .ledgerTransaction(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .LedgerTransactionCreateRequest
                                    .builder()
                                    .ledgerEntries(
                                        listOf(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .LedgerTransactionCreateRequest
                                                .LedgerEntryCreateRequest
                                                .builder()
                                                .amount(123L)
                                                .direction(TransactionDirection.CREDIT)
                                                .ledgerAccountId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .availableBalanceAmount(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .LedgerTransactionCreateRequest
                                                        .LedgerEntryCreateRequest
                                                        .AvailableBalanceAmount
                                                        .builder()
                                                        .build()
                                                )
                                                .lockVersion(123L)
                                                .metadata(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .LedgerTransactionCreateRequest
                                                        .LedgerEntryCreateRequest
                                                        .Metadata
                                                        .builder()
                                                        .build()
                                                )
                                                .pendingBalanceAmount(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .LedgerTransactionCreateRequest
                                                        .LedgerEntryCreateRequest
                                                        .PendingBalanceAmount
                                                        .builder()
                                                        .build()
                                                )
                                                .postedBalanceAmount(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .LedgerTransactionCreateRequest
                                                        .LedgerEntryCreateRequest
                                                        .PostedBalanceAmount
                                                        .builder()
                                                        .build()
                                                )
                                                .showResultingLedgerAccountBalances(true)
                                                .build()
                                        )
                                    )
                                    .description("string")
                                    .effectiveAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .effectiveDate(LocalDate.parse("2019-12-27"))
                                    .externalId("string")
                                    .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .ledgerableType(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .LedgerTransactionCreateRequest
                                            .LedgerableType
                                            .COUNTERPARTY
                                    )
                                    .metadata(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .LedgerTransactionCreateRequest
                                            .Metadata
                                            .builder()
                                            .build()
                                    )
                                    .status(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .LedgerTransactionCreateRequest
                                            .Status
                                            .ARCHIVED
                                    )
                                    .build()
                            )
                            .ledgerTransactionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .lineItems(
                                listOf(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .LineItemRequest
                                        .builder()
                                        .amount(123L)
                                        .accountingCategoryId("string")
                                        .description("string")
                                        .metadata(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .LineItemRequest
                                                .Metadata
                                                .builder()
                                                .build()
                                        )
                                        .build()
                                )
                            )
                            .metadata(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .Metadata
                                    .builder()
                                    .build()
                            )
                            .nsfProtected(true)
                            .originatingPartyName("string")
                            .priority(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .Priority
                                    .HIGH
                            )
                            .purpose("string")
                            .receivingAccount(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .ReceivingAccount
                                    .builder()
                                    .accountDetails(
                                        listOf(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .ReceivingAccount
                                                .AccountDetail
                                                .builder()
                                                .accountNumber("string")
                                                .accountNumberType(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .ReceivingAccount
                                                        .AccountDetail
                                                        .AccountNumberType
                                                        .IBAN
                                                )
                                                .build()
                                        )
                                    )
                                    .accountType(ExternalAccountType.CASH)
                                    .contactDetails(
                                        listOf(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .ReceivingAccount
                                                .ContactDetailCreateRequest
                                                .builder()
                                                .contactIdentifier("string")
                                                .contactIdentifierType(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .ReceivingAccount
                                                        .ContactDetailCreateRequest
                                                        .ContactIdentifierType
                                                        .EMAIL
                                                )
                                                .build()
                                        )
                                    )
                                    .ledgerAccount(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .ReceivingAccount
                                            .LedgerAccountCreateRequest
                                            .builder()
                                            .currency("string")
                                            .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .name("string")
                                            .normalBalance(TransactionDirection.CREDIT)
                                            .currencyExponent(123L)
                                            .description("string")
                                            .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .ledgerableType(
                                                BulkRequestCreateParams.Resource
                                                    .PaymentOrderAsyncCreateRequest
                                                    .ReceivingAccount
                                                    .LedgerAccountCreateRequest
                                                    .LedgerableType
                                                    .EXTERNAL_ACCOUNT
                                            )
                                            .metadata(
                                                BulkRequestCreateParams.Resource
                                                    .PaymentOrderAsyncCreateRequest
                                                    .ReceivingAccount
                                                    .LedgerAccountCreateRequest
                                                    .Metadata
                                                    .builder()
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .metadata(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .ReceivingAccount
                                            .Metadata
                                            .builder()
                                            .build()
                                    )
                                    .name("string")
                                    .partyAddress(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .ReceivingAccount
                                            .AddressRequest
                                            .builder()
                                            .country("string")
                                            .line1("string")
                                            .line2("string")
                                            .locality("string")
                                            .postalCode("string")
                                            .region("string")
                                            .build()
                                    )
                                    .partyIdentifier("string")
                                    .partyName("string")
                                    .partyType(
                                        BulkRequestCreateParams.Resource
                                            .PaymentOrderAsyncCreateRequest
                                            .ReceivingAccount
                                            .PartyType
                                            .BUSINESS
                                    )
                                    .plaidProcessorToken("string")
                                    .routingDetails(
                                        listOf(
                                            BulkRequestCreateParams.Resource
                                                .PaymentOrderAsyncCreateRequest
                                                .ReceivingAccount
                                                .RoutingDetail
                                                .builder()
                                                .routingNumber("string")
                                                .routingNumberType(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .ReceivingAccount
                                                        .RoutingDetail
                                                        .RoutingNumberType
                                                        .ABA
                                                )
                                                .paymentType(
                                                    BulkRequestCreateParams.Resource
                                                        .PaymentOrderAsyncCreateRequest
                                                        .ReceivingAccount
                                                        .RoutingDetail
                                                        .PaymentType
                                                        .ACH
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .receivingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .remittanceInformation("string")
                            .sendRemittanceAdvice(true)
                            .statementDescriptor("string")
                            .subtype(PaymentOrderSubtype.BACS_NEW_INSTRUCTION)
                            .transactionMonitoringEnabled(true)
                            .ultimateOriginatingPartyIdentifier("string")
                            .ultimateOriginatingPartyName("string")
                            .ultimateReceivingPartyIdentifier("string")
                            .ultimateReceivingPartyName("string")
                            .build()
                    )
                )
            )
        assertThat(body.metadata()).isEqualTo(BulkRequestCreateParams.Metadata.builder().build())
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            BulkRequestCreateParams.builder()
                .actionType(BulkRequestCreateParams.ActionType.CREATE)
                .resourceType(BulkRequestCreateParams.ResourceType.PAYMENT_ORDER)
                .resources(
                    listOf(
                        BulkRequestCreateParams.Resource.ofPaymentOrderAsyncCreateRequest(
                            BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                .builder()
                                .amount(123L)
                                .direction(
                                    BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                        .Direction
                                        .CREDIT
                                )
                                .originatingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .type(PaymentOrderType.ACH)
                                .build()
                        )
                    )
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.actionType()).isEqualTo(BulkRequestCreateParams.ActionType.CREATE)
        assertThat(body.resourceType())
            .isEqualTo(BulkRequestCreateParams.ResourceType.PAYMENT_ORDER)
        assertThat(body.resources())
            .isEqualTo(
                listOf(
                    BulkRequestCreateParams.Resource.ofPaymentOrderAsyncCreateRequest(
                        BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest.builder()
                            .amount(123L)
                            .direction(
                                BulkRequestCreateParams.Resource.PaymentOrderAsyncCreateRequest
                                    .Direction
                                    .CREDIT
                            )
                            .originatingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .type(PaymentOrderType.ACH)
                            .build()
                    )
                )
            )
    }
}
