// File generated from our OpenAPI spec by Stainless.

package com.moderntreasury.api.models

import com.moderntreasury.api.models.*
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CounterpartyCreateParamsTest {

    @Test
    fun createCounterpartyCreateParams() {
        CounterpartyCreateParams.builder()
            .name("string")
            .accounting(
                CounterpartyCreateParams.Accounting.builder()
                    .type(CounterpartyCreateParams.Accounting.Type.CUSTOMER)
                    .build()
            )
            .accounts(
                listOf(
                    CounterpartyCreateParams.Account.builder()
                        .accountDetails(
                            listOf(
                                CounterpartyCreateParams.Account.AccountDetail.builder()
                                    .accountNumber("string")
                                    .accountNumberType(
                                        CounterpartyCreateParams.Account.AccountDetail
                                            .AccountNumberType
                                            .IBAN
                                    )
                                    .build()
                            )
                        )
                        .accountType(ExternalAccountType.CASH)
                        .contactDetails(
                            listOf(
                                CounterpartyCreateParams.Account.ContactDetailCreateRequest
                                    .builder()
                                    .contactIdentifier("string")
                                    .contactIdentifierType(
                                        CounterpartyCreateParams.Account.ContactDetailCreateRequest
                                            .ContactIdentifierType
                                            .EMAIL
                                    )
                                    .build()
                            )
                        )
                        .ledgerAccount(
                            CounterpartyCreateParams.Account.LedgerAccountCreateRequest.builder()
                                .currency("string")
                                .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("string")
                                .normalBalance(TransactionDirection.CREDIT)
                                .currencyExponent(123L)
                                .description("string")
                                .ledgerAccountCategoryIds(
                                    listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                )
                                .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .ledgerableType(
                                    CounterpartyCreateParams.Account.LedgerAccountCreateRequest
                                        .LedgerableType
                                        .EXTERNAL_ACCOUNT
                                )
                                .metadata(
                                    CounterpartyCreateParams.Account.LedgerAccountCreateRequest
                                        .Metadata
                                        .builder()
                                        .build()
                                )
                                .build()
                        )
                        .metadata(CounterpartyCreateParams.Account.Metadata.builder().build())
                        .name("string")
                        .partyAddress(
                            CounterpartyCreateParams.Account.AddressRequest.builder()
                                .country("string")
                                .line1("string")
                                .line2("string")
                                .locality("string")
                                .postalCode("string")
                                .region("string")
                                .build()
                        )
                        .partyIdentifier("string")
                        .partyName("string")
                        .partyType(CounterpartyCreateParams.Account.PartyType.BUSINESS)
                        .plaidProcessorToken("string")
                        .routingDetails(
                            listOf(
                                CounterpartyCreateParams.Account.RoutingDetail.builder()
                                    .routingNumber("string")
                                    .routingNumberType(
                                        CounterpartyCreateParams.Account.RoutingDetail
                                            .RoutingNumberType
                                            .ABA
                                    )
                                    .paymentType(
                                        CounterpartyCreateParams.Account.RoutingDetail.PaymentType
                                            .ACH
                                    )
                                    .build()
                            )
                        )
                        .build()
                )
            )
            .email("dev@stainlessapi.com")
            .ledgerType(CounterpartyCreateParams.LedgerType.CUSTOMER)
            .metadata(CounterpartyCreateParams.Metadata.builder().build())
            .sendRemittanceAdvice(true)
            .taxpayerIdentifier("string")
            .verificationStatus(CounterpartyCreateParams.VerificationStatus.DENIED)
            .build()
    }

    @Test
    fun getBody() {
        val params =
            CounterpartyCreateParams.builder()
                .name("string")
                .accounting(
                    CounterpartyCreateParams.Accounting.builder()
                        .type(CounterpartyCreateParams.Accounting.Type.CUSTOMER)
                        .build()
                )
                .accounts(
                    listOf(
                        CounterpartyCreateParams.Account.builder()
                            .accountDetails(
                                listOf(
                                    CounterpartyCreateParams.Account.AccountDetail.builder()
                                        .accountNumber("string")
                                        .accountNumberType(
                                            CounterpartyCreateParams.Account.AccountDetail
                                                .AccountNumberType
                                                .IBAN
                                        )
                                        .build()
                                )
                            )
                            .accountType(ExternalAccountType.CASH)
                            .contactDetails(
                                listOf(
                                    CounterpartyCreateParams.Account.ContactDetailCreateRequest
                                        .builder()
                                        .contactIdentifier("string")
                                        .contactIdentifierType(
                                            CounterpartyCreateParams.Account
                                                .ContactDetailCreateRequest
                                                .ContactIdentifierType
                                                .EMAIL
                                        )
                                        .build()
                                )
                            )
                            .ledgerAccount(
                                CounterpartyCreateParams.Account.LedgerAccountCreateRequest
                                    .builder()
                                    .currency("string")
                                    .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .name("string")
                                    .normalBalance(TransactionDirection.CREDIT)
                                    .currencyExponent(123L)
                                    .description("string")
                                    .ledgerAccountCategoryIds(
                                        listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    )
                                    .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .ledgerableType(
                                        CounterpartyCreateParams.Account.LedgerAccountCreateRequest
                                            .LedgerableType
                                            .EXTERNAL_ACCOUNT
                                    )
                                    .metadata(
                                        CounterpartyCreateParams.Account.LedgerAccountCreateRequest
                                            .Metadata
                                            .builder()
                                            .build()
                                    )
                                    .build()
                            )
                            .metadata(CounterpartyCreateParams.Account.Metadata.builder().build())
                            .name("string")
                            .partyAddress(
                                CounterpartyCreateParams.Account.AddressRequest.builder()
                                    .country("string")
                                    .line1("string")
                                    .line2("string")
                                    .locality("string")
                                    .postalCode("string")
                                    .region("string")
                                    .build()
                            )
                            .partyIdentifier("string")
                            .partyName("string")
                            .partyType(CounterpartyCreateParams.Account.PartyType.BUSINESS)
                            .plaidProcessorToken("string")
                            .routingDetails(
                                listOf(
                                    CounterpartyCreateParams.Account.RoutingDetail.builder()
                                        .routingNumber("string")
                                        .routingNumberType(
                                            CounterpartyCreateParams.Account.RoutingDetail
                                                .RoutingNumberType
                                                .ABA
                                        )
                                        .paymentType(
                                            CounterpartyCreateParams.Account.RoutingDetail
                                                .PaymentType
                                                .ACH
                                        )
                                        .build()
                                )
                            )
                            .build()
                    )
                )
                .email("dev@stainlessapi.com")
                .ledgerType(CounterpartyCreateParams.LedgerType.CUSTOMER)
                .metadata(CounterpartyCreateParams.Metadata.builder().build())
                .sendRemittanceAdvice(true)
                .taxpayerIdentifier("string")
                .verificationStatus(CounterpartyCreateParams.VerificationStatus.DENIED)
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.name()).isEqualTo("string")
        assertThat(body.accounting())
            .isEqualTo(
                CounterpartyCreateParams.Accounting.builder()
                    .type(CounterpartyCreateParams.Accounting.Type.CUSTOMER)
                    .build()
            )
        assertThat(body.accounts())
            .isEqualTo(
                listOf(
                    CounterpartyCreateParams.Account.builder()
                        .accountDetails(
                            listOf(
                                CounterpartyCreateParams.Account.AccountDetail.builder()
                                    .accountNumber("string")
                                    .accountNumberType(
                                        CounterpartyCreateParams.Account.AccountDetail
                                            .AccountNumberType
                                            .IBAN
                                    )
                                    .build()
                            )
                        )
                        .accountType(ExternalAccountType.CASH)
                        .contactDetails(
                            listOf(
                                CounterpartyCreateParams.Account.ContactDetailCreateRequest
                                    .builder()
                                    .contactIdentifier("string")
                                    .contactIdentifierType(
                                        CounterpartyCreateParams.Account.ContactDetailCreateRequest
                                            .ContactIdentifierType
                                            .EMAIL
                                    )
                                    .build()
                            )
                        )
                        .ledgerAccount(
                            CounterpartyCreateParams.Account.LedgerAccountCreateRequest.builder()
                                .currency("string")
                                .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("string")
                                .normalBalance(TransactionDirection.CREDIT)
                                .currencyExponent(123L)
                                .description("string")
                                .ledgerAccountCategoryIds(
                                    listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                )
                                .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .ledgerableType(
                                    CounterpartyCreateParams.Account.LedgerAccountCreateRequest
                                        .LedgerableType
                                        .EXTERNAL_ACCOUNT
                                )
                                .metadata(
                                    CounterpartyCreateParams.Account.LedgerAccountCreateRequest
                                        .Metadata
                                        .builder()
                                        .build()
                                )
                                .build()
                        )
                        .metadata(CounterpartyCreateParams.Account.Metadata.builder().build())
                        .name("string")
                        .partyAddress(
                            CounterpartyCreateParams.Account.AddressRequest.builder()
                                .country("string")
                                .line1("string")
                                .line2("string")
                                .locality("string")
                                .postalCode("string")
                                .region("string")
                                .build()
                        )
                        .partyIdentifier("string")
                        .partyName("string")
                        .partyType(CounterpartyCreateParams.Account.PartyType.BUSINESS)
                        .plaidProcessorToken("string")
                        .routingDetails(
                            listOf(
                                CounterpartyCreateParams.Account.RoutingDetail.builder()
                                    .routingNumber("string")
                                    .routingNumberType(
                                        CounterpartyCreateParams.Account.RoutingDetail
                                            .RoutingNumberType
                                            .ABA
                                    )
                                    .paymentType(
                                        CounterpartyCreateParams.Account.RoutingDetail.PaymentType
                                            .ACH
                                    )
                                    .build()
                            )
                        )
                        .build()
                )
            )
        assertThat(body.email()).isEqualTo("dev@stainlessapi.com")
        assertThat(body.ledgerType()).isEqualTo(CounterpartyCreateParams.LedgerType.CUSTOMER)
        assertThat(body.metadata()).isEqualTo(CounterpartyCreateParams.Metadata.builder().build())
        assertThat(body.sendRemittanceAdvice()).isEqualTo(true)
        assertThat(body.taxpayerIdentifier()).isEqualTo("string")
        assertThat(body.verificationStatus())
            .isEqualTo(CounterpartyCreateParams.VerificationStatus.DENIED)
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params = CounterpartyCreateParams.builder().build()
        val body = params.getBody()
        assertThat(body).isNotNull
    }
}
