package com.moderntreasury.api.models

import com.moderntreasury.api.models.*
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ExternalAccountCreateParamsTest {

    @Test
    fun createExternalAccountCreateParams() {
        ExternalAccountCreateParams.builder()
            .accountType(ExternalAccountType.CASH)
            .partyType(ExternalAccountCreateParams.PartyType.BUSINESS)
            .partyAddress(
                ExternalAccountCreateParams.AddressRequest.builder()
                    .country("string")
                    .line1("string")
                    .line2("string")
                    .locality("string")
                    .postalCode("string")
                    .region("string")
                    .build()
            )
            .name("string")
            .counterpartyId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .accountDetails(
                listOf(
                    ExternalAccountCreateParams.AccountDetail.builder()
                        .accountNumber("string")
                        .accountNumberType(
                            ExternalAccountCreateParams.AccountDetail.AccountNumberType.IBAN
                        )
                        .build()
                )
            )
            .routingDetails(
                listOf(
                    ExternalAccountCreateParams.RoutingDetail.builder()
                        .routingNumber("string")
                        .routingNumberType(
                            ExternalAccountCreateParams.RoutingDetail.RoutingNumberType.ABA
                        )
                        .paymentType(ExternalAccountCreateParams.RoutingDetail.PaymentType.ACH)
                        .build()
                )
            )
            .metadata(ExternalAccountCreateParams.Metadata.builder().build())
            .partyName("string")
            .partyIdentifier("string")
            .ledgerAccount(
                ExternalAccountCreateParams.LedgerAccountCreateRequest.builder()
                    .currency("string")
                    .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .name("string")
                    .normalBalance(
                        ExternalAccountCreateParams.LedgerAccountCreateRequest.NormalBalance.CREDIT
                    )
                    .currencyExponent(123L)
                    .description("string")
                    .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .ledgerableType(
                        ExternalAccountCreateParams.LedgerAccountCreateRequest.LedgerableType
                            .EXTERNAL_ACCOUNT
                    )
                    .metadata(
                        ExternalAccountCreateParams.LedgerAccountCreateRequest.Metadata.builder()
                            .build()
                    )
                    .build()
            )
            .plaidProcessorToken("string")
            .contactDetails(
                listOf(
                    ExternalAccountCreateParams.ContactDetailCreateRequest.builder()
                        .contactIdentifier("string")
                        .contactIdentifierType(
                            ExternalAccountCreateParams.ContactDetailCreateRequest
                                .ContactIdentifierType
                                .EMAIL
                        )
                        .build()
                )
            )
            .build()
    }

    @Test
    fun getBody() {
        val params =
            ExternalAccountCreateParams.builder()
                .accountType(ExternalAccountType.CASH)
                .partyType(ExternalAccountCreateParams.PartyType.BUSINESS)
                .partyAddress(
                    ExternalAccountCreateParams.AddressRequest.builder()
                        .country("string")
                        .line1("string")
                        .line2("string")
                        .locality("string")
                        .postalCode("string")
                        .region("string")
                        .build()
                )
                .name("string")
                .counterpartyId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .accountDetails(
                    listOf(
                        ExternalAccountCreateParams.AccountDetail.builder()
                            .accountNumber("string")
                            .accountNumberType(
                                ExternalAccountCreateParams.AccountDetail.AccountNumberType.IBAN
                            )
                            .build()
                    )
                )
                .routingDetails(
                    listOf(
                        ExternalAccountCreateParams.RoutingDetail.builder()
                            .routingNumber("string")
                            .routingNumberType(
                                ExternalAccountCreateParams.RoutingDetail.RoutingNumberType.ABA
                            )
                            .paymentType(ExternalAccountCreateParams.RoutingDetail.PaymentType.ACH)
                            .build()
                    )
                )
                .metadata(ExternalAccountCreateParams.Metadata.builder().build())
                .partyName("string")
                .partyIdentifier("string")
                .ledgerAccount(
                    ExternalAccountCreateParams.LedgerAccountCreateRequest.builder()
                        .currency("string")
                        .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .name("string")
                        .normalBalance(
                            ExternalAccountCreateParams.LedgerAccountCreateRequest.NormalBalance
                                .CREDIT
                        )
                        .currencyExponent(123L)
                        .description("string")
                        .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .ledgerableType(
                            ExternalAccountCreateParams.LedgerAccountCreateRequest.LedgerableType
                                .EXTERNAL_ACCOUNT
                        )
                        .metadata(
                            ExternalAccountCreateParams.LedgerAccountCreateRequest.Metadata
                                .builder()
                                .build()
                        )
                        .build()
                )
                .plaidProcessorToken("string")
                .contactDetails(
                    listOf(
                        ExternalAccountCreateParams.ContactDetailCreateRequest.builder()
                            .contactIdentifier("string")
                            .contactIdentifierType(
                                ExternalAccountCreateParams.ContactDetailCreateRequest
                                    .ContactIdentifierType
                                    .EMAIL
                            )
                            .build()
                    )
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.accountType()).isEqualTo(ExternalAccountType.CASH)
        assertThat(body.partyType()).isEqualTo(ExternalAccountCreateParams.PartyType.BUSINESS)
        assertThat(body.partyAddress())
            .isEqualTo(
                ExternalAccountCreateParams.AddressRequest.builder()
                    .country("string")
                    .line1("string")
                    .line2("string")
                    .locality("string")
                    .postalCode("string")
                    .region("string")
                    .build()
            )
        assertThat(body.name()).isEqualTo("string")
        assertThat(body.counterpartyId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.accountDetails())
            .isEqualTo(
                listOf(
                    ExternalAccountCreateParams.AccountDetail.builder()
                        .accountNumber("string")
                        .accountNumberType(
                            ExternalAccountCreateParams.AccountDetail.AccountNumberType.IBAN
                        )
                        .build()
                )
            )
        assertThat(body.routingDetails())
            .isEqualTo(
                listOf(
                    ExternalAccountCreateParams.RoutingDetail.builder()
                        .routingNumber("string")
                        .routingNumberType(
                            ExternalAccountCreateParams.RoutingDetail.RoutingNumberType.ABA
                        )
                        .paymentType(ExternalAccountCreateParams.RoutingDetail.PaymentType.ACH)
                        .build()
                )
            )
        assertThat(body.metadata())
            .isEqualTo(ExternalAccountCreateParams.Metadata.builder().build())
        assertThat(body.partyName()).isEqualTo("string")
        assertThat(body.partyIdentifier()).isEqualTo("string")
        assertThat(body.ledgerAccount())
            .isEqualTo(
                ExternalAccountCreateParams.LedgerAccountCreateRequest.builder()
                    .currency("string")
                    .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .name("string")
                    .normalBalance(
                        ExternalAccountCreateParams.LedgerAccountCreateRequest.NormalBalance.CREDIT
                    )
                    .currencyExponent(123L)
                    .description("string")
                    .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .ledgerableType(
                        ExternalAccountCreateParams.LedgerAccountCreateRequest.LedgerableType
                            .EXTERNAL_ACCOUNT
                    )
                    .metadata(
                        ExternalAccountCreateParams.LedgerAccountCreateRequest.Metadata.builder()
                            .build()
                    )
                    .build()
            )
        assertThat(body.plaidProcessorToken()).isEqualTo("string")
        assertThat(body.contactDetails())
            .isEqualTo(
                listOf(
                    ExternalAccountCreateParams.ContactDetailCreateRequest.builder()
                        .contactIdentifier("string")
                        .contactIdentifierType(
                            ExternalAccountCreateParams.ContactDetailCreateRequest
                                .ContactIdentifierType
                                .EMAIL
                        )
                        .build()
                )
            )
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params = ExternalAccountCreateParams.builder().build()
        val body = params.getBody()
        assertThat(body).isNotNull
    }
}
