// File generated from our OpenAPI spec by Stainless.

package com.moderntreasury.api.models

import com.moderntreasury.api.models.*
import java.time.LocalDate
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class LegalEntityAssociationCreateParamsTest {

    @Test
    fun createLegalEntityAssociationCreateParams() {
        LegalEntityAssociationCreateParams.builder()
            .parentLegalEntityId("parent_legal_entity_id")
            .relationshipTypes(
                listOf(LegalEntityAssociationCreateParams.RelationshipType.BENEFICIAL_OWNER)
            )
            .childLegalEntity(
                LegalEntityAssociationCreateParams.ChildLegalEntityCreate.builder()
                    .addresses(
                        listOf(
                            LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                .LegalEntityAddressCreateRequest
                                .builder()
                                .country("country")
                                .line1("line1")
                                .locality("locality")
                                .postalCode("postal_code")
                                .region("region")
                                .addressTypes(
                                    listOf(
                                        LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                            .LegalEntityAddressCreateRequest
                                            .AddressType
                                            .BUSINESS
                                    )
                                )
                                .line2("line2")
                                .build()
                        )
                    )
                    .businessName("business_name")
                    .dateFormed(LocalDate.parse("2019-12-27"))
                    .dateOfBirth(LocalDate.parse("2019-12-27"))
                    .doingBusinessAsNames(listOf("string"))
                    .email("email")
                    .firstName("first_name")
                    .identifications(
                        listOf(
                            LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                .IdentificationCreateRequest
                                .builder()
                                .idNumber("id_number")
                                .idType(
                                    LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                        .IdentificationCreateRequest
                                        .IdType
                                        .AR_CUIL
                                )
                                .issuingCountry("issuing_country")
                                .build()
                        )
                    )
                    .lastName("last_name")
                    .legalEntityType(
                        LegalEntityAssociationCreateParams.ChildLegalEntityCreate.LegalEntityType
                            .BUSINESS
                    )
                    .legalStructure(
                        LegalEntityAssociationCreateParams.ChildLegalEntityCreate.LegalStructure
                            .CORPORATION
                    )
                    .metadata(
                        LegalEntityAssociationCreateParams.ChildLegalEntityCreate.Metadata.builder()
                            .build()
                    )
                    .phoneNumbers(
                        listOf(
                            LegalEntityAssociationCreateParams.ChildLegalEntityCreate.PhoneNumber
                                .builder()
                                .phoneNumber("phone_number")
                                .build()
                        )
                    )
                    .riskRating(
                        LegalEntityAssociationCreateParams.ChildLegalEntityCreate.RiskRating.LOW
                    )
                    .website("website")
                    .build()
            )
            .childLegalEntityId("child_legal_entity_id")
            .ownershipPercentage(123L)
            .title("title")
            .build()
    }

    @Test
    fun getBody() {
        val params =
            LegalEntityAssociationCreateParams.builder()
                .parentLegalEntityId("parent_legal_entity_id")
                .relationshipTypes(
                    listOf(LegalEntityAssociationCreateParams.RelationshipType.BENEFICIAL_OWNER)
                )
                .childLegalEntity(
                    LegalEntityAssociationCreateParams.ChildLegalEntityCreate.builder()
                        .addresses(
                            listOf(
                                LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                    .LegalEntityAddressCreateRequest
                                    .builder()
                                    .country("country")
                                    .line1("line1")
                                    .locality("locality")
                                    .postalCode("postal_code")
                                    .region("region")
                                    .addressTypes(
                                        listOf(
                                            LegalEntityAssociationCreateParams
                                                .ChildLegalEntityCreate
                                                .LegalEntityAddressCreateRequest
                                                .AddressType
                                                .BUSINESS
                                        )
                                    )
                                    .line2("line2")
                                    .build()
                            )
                        )
                        .businessName("business_name")
                        .dateFormed(LocalDate.parse("2019-12-27"))
                        .dateOfBirth(LocalDate.parse("2019-12-27"))
                        .doingBusinessAsNames(listOf("string"))
                        .email("email")
                        .firstName("first_name")
                        .identifications(
                            listOf(
                                LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                    .IdentificationCreateRequest
                                    .builder()
                                    .idNumber("id_number")
                                    .idType(
                                        LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                            .IdentificationCreateRequest
                                            .IdType
                                            .AR_CUIL
                                    )
                                    .issuingCountry("issuing_country")
                                    .build()
                            )
                        )
                        .lastName("last_name")
                        .legalEntityType(
                            LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                .LegalEntityType
                                .BUSINESS
                        )
                        .legalStructure(
                            LegalEntityAssociationCreateParams.ChildLegalEntityCreate.LegalStructure
                                .CORPORATION
                        )
                        .metadata(
                            LegalEntityAssociationCreateParams.ChildLegalEntityCreate.Metadata
                                .builder()
                                .build()
                        )
                        .phoneNumbers(
                            listOf(
                                LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                    .PhoneNumber
                                    .builder()
                                    .phoneNumber("phone_number")
                                    .build()
                            )
                        )
                        .riskRating(
                            LegalEntityAssociationCreateParams.ChildLegalEntityCreate.RiskRating.LOW
                        )
                        .website("website")
                        .build()
                )
                .childLegalEntityId("child_legal_entity_id")
                .ownershipPercentage(123L)
                .title("title")
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.parentLegalEntityId()).isEqualTo("parent_legal_entity_id")
        assertThat(body.relationshipTypes())
            .isEqualTo(listOf(LegalEntityAssociationCreateParams.RelationshipType.BENEFICIAL_OWNER))
        assertThat(body.childLegalEntity())
            .isEqualTo(
                LegalEntityAssociationCreateParams.ChildLegalEntityCreate.builder()
                    .addresses(
                        listOf(
                            LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                .LegalEntityAddressCreateRequest
                                .builder()
                                .country("country")
                                .line1("line1")
                                .locality("locality")
                                .postalCode("postal_code")
                                .region("region")
                                .addressTypes(
                                    listOf(
                                        LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                            .LegalEntityAddressCreateRequest
                                            .AddressType
                                            .BUSINESS
                                    )
                                )
                                .line2("line2")
                                .build()
                        )
                    )
                    .businessName("business_name")
                    .dateFormed(LocalDate.parse("2019-12-27"))
                    .dateOfBirth(LocalDate.parse("2019-12-27"))
                    .doingBusinessAsNames(listOf("string"))
                    .email("email")
                    .firstName("first_name")
                    .identifications(
                        listOf(
                            LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                .IdentificationCreateRequest
                                .builder()
                                .idNumber("id_number")
                                .idType(
                                    LegalEntityAssociationCreateParams.ChildLegalEntityCreate
                                        .IdentificationCreateRequest
                                        .IdType
                                        .AR_CUIL
                                )
                                .issuingCountry("issuing_country")
                                .build()
                        )
                    )
                    .lastName("last_name")
                    .legalEntityType(
                        LegalEntityAssociationCreateParams.ChildLegalEntityCreate.LegalEntityType
                            .BUSINESS
                    )
                    .legalStructure(
                        LegalEntityAssociationCreateParams.ChildLegalEntityCreate.LegalStructure
                            .CORPORATION
                    )
                    .metadata(
                        LegalEntityAssociationCreateParams.ChildLegalEntityCreate.Metadata.builder()
                            .build()
                    )
                    .phoneNumbers(
                        listOf(
                            LegalEntityAssociationCreateParams.ChildLegalEntityCreate.PhoneNumber
                                .builder()
                                .phoneNumber("phone_number")
                                .build()
                        )
                    )
                    .riskRating(
                        LegalEntityAssociationCreateParams.ChildLegalEntityCreate.RiskRating.LOW
                    )
                    .website("website")
                    .build()
            )
        assertThat(body.childLegalEntityId()).isEqualTo("child_legal_entity_id")
        assertThat(body.ownershipPercentage()).isEqualTo(123L)
        assertThat(body.title()).isEqualTo("title")
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            LegalEntityAssociationCreateParams.builder()
                .parentLegalEntityId("parent_legal_entity_id")
                .relationshipTypes(
                    listOf(LegalEntityAssociationCreateParams.RelationshipType.BENEFICIAL_OWNER)
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.parentLegalEntityId()).isEqualTo("parent_legal_entity_id")
        assertThat(body.relationshipTypes())
            .isEqualTo(listOf(LegalEntityAssociationCreateParams.RelationshipType.BENEFICIAL_OWNER))
    }
}
