// File generated from our OpenAPI spec by Stainless.

package com.moderntreasury.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.moderntreasury.api.core.JsonValue
import com.moderntreasury.api.core.jsonMapper
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class LegalEntityCreateTest {

    @Test
    fun create() {
        val legalEntityCreate =
            LegalEntityCreate.builder()
                .legalEntityType(LegalEntityCreate.LegalEntityType.BUSINESS)
                .addAddress(
                    LegalEntityAddressCreateRequest.builder()
                        .country("country")
                        .line1("line1")
                        .locality("locality")
                        .postalCode("postal_code")
                        .region("region")
                        .addAddressType(LegalEntityAddressCreateRequest.AddressType.BUSINESS)
                        .line2("line2")
                        .build()
                )
                .bankSettings(
                    LegalEntityCreate.LegalEntityBankSetting.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .backupWithholdingPercentage(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .enableBackupWithholding(true)
                        .liveMode(true)
                        .object_("object")
                        .privacyOptOut(true)
                        .regulationO(true)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .businessDescription("business_description")
                .businessName("business_name")
                .citizenshipCountry("citizenship_country")
                .complianceDetails(
                    LegalEntityComplianceDetail.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .issuer("issuer")
                        .liveMode(true)
                        .object_("object")
                        .tokenExpiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .tokenIssuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .tokenUrl("token_url")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .entityValidated(true)
                        .validatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .countryOfIncorporation("country_of_incorporation")
                .dateFormed(LocalDate.parse("2019-12-27"))
                .dateOfBirth(LocalDate.parse("2019-12-27"))
                .addDoingBusinessAsName("string")
                .email("email")
                .expectedActivityVolume(0L)
                .firstName("first_name")
                .addIdentification(
                    IdentificationCreateRequest.builder()
                        .idNumber("id_number")
                        .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                        .expirationDate(LocalDate.parse("2019-12-27"))
                        .issuingCountry("issuing_country")
                        .issuingRegion("issuing_region")
                        .build()
                )
                .addIndustryClassification(
                    LegalEntityIndustryClassification.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addClassificationCode("string")
                        .classificationType(
                            LegalEntityIndustryClassification.ClassificationType.ANZSIC
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .liveMode(true)
                        .object_("object")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .intendedUse("intended_use")
                .lastName("last_name")
                .addLegalEntityAssociation(
                    LegalEntityAssociationInlineCreate.builder()
                        .addRelationshipType(
                            LegalEntityAssociationInlineCreate.RelationshipType.AUTHORIZED_SIGNER
                        )
                        .childLegalEntity(
                            ChildLegalEntityCreate.builder()
                                .addAddress(
                                    LegalEntityAddressCreateRequest.builder()
                                        .country("country")
                                        .line1("line1")
                                        .locality("locality")
                                        .postalCode("postal_code")
                                        .region("region")
                                        .addAddressType(
                                            LegalEntityAddressCreateRequest.AddressType.BUSINESS
                                        )
                                        .line2("line2")
                                        .build()
                                )
                                .bankSettings(
                                    ChildLegalEntityCreate.LegalEntityBankSetting.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .backupWithholdingPercentage(0L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .enableBackupWithholding(true)
                                        .liveMode(true)
                                        .object_("object")
                                        .privacyOptOut(true)
                                        .regulationO(true)
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .businessDescription("business_description")
                                .businessName("business_name")
                                .citizenshipCountry("citizenship_country")
                                .complianceDetails(
                                    LegalEntityComplianceDetail.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .issuer("issuer")
                                        .liveMode(true)
                                        .object_("object")
                                        .tokenExpiresAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .tokenIssuedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .tokenUrl("token_url")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .entityValidated(true)
                                        .validatedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .countryOfIncorporation("country_of_incorporation")
                                .dateFormed(LocalDate.parse("2019-12-27"))
                                .dateOfBirth(LocalDate.parse("2019-12-27"))
                                .addDoingBusinessAsName("string")
                                .email("email")
                                .expectedActivityVolume(0L)
                                .firstName("first_name")
                                .addIdentification(
                                    IdentificationCreateRequest.builder()
                                        .idNumber("id_number")
                                        .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                                        .expirationDate(LocalDate.parse("2019-12-27"))
                                        .issuingCountry("issuing_country")
                                        .issuingRegion("issuing_region")
                                        .build()
                                )
                                .addIndustryClassification(
                                    LegalEntityIndustryClassification.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .addClassificationCode("string")
                                        .classificationType(
                                            LegalEntityIndustryClassification.ClassificationType
                                                .ANZSIC
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .intendedUse("intended_use")
                                .lastName("last_name")
                                .legalEntityAssociations(listOf())
                                .legalEntityType(ChildLegalEntityCreate.LegalEntityType.BUSINESS)
                                .legalStructure(ChildLegalEntityCreate.LegalStructure.CORPORATION)
                                .metadata(
                                    ChildLegalEntityCreate.Metadata.builder()
                                        .putAdditionalProperty("key", JsonValue.from("value"))
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .putAdditionalProperty("modern", JsonValue.from("treasury"))
                                        .build()
                                )
                                .middleName("middle_name")
                                .addOperatingJurisdiction("string")
                                .addPhoneNumber(
                                    ChildLegalEntityCreate.PhoneNumber.builder()
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .politicallyExposedPerson(true)
                                .preferredName("preferred_name")
                                .prefix("prefix")
                                .addPrimarySocialMediaSite("string")
                                .riskRating(ChildLegalEntityCreate.RiskRating.LOW)
                                .suffix("suffix")
                                .wealthAndEmploymentDetails(
                                    ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                        .builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .annualIncome(0L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .employerCountry("employer_country")
                                        .employerName("employer_name")
                                        .employerState("employer_state")
                                        .employmentStatus(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .EmploymentStatus
                                                .EMPLOYED
                                        )
                                        .incomeCountry("income_country")
                                        .incomeSource(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .IncomeSource
                                                .FAMILY_SUPPORT
                                        )
                                        .incomeState("income_state")
                                        .industry(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .Industry
                                                .ACCOUNTING
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .occupation(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .Occupation
                                                .CONSULTING
                                        )
                                        .sourceOfFunds(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .SourceOfFunds
                                                .ALIMONY
                                        )
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .wealthSource(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .WealthSource
                                                .BUSINESS_SALE
                                        )
                                        .build()
                                )
                                .website("website")
                                .build()
                        )
                        .childLegalEntityId("child_legal_entity_id")
                        .ownershipPercentage(0L)
                        .title("title")
                        .build()
                )
                .legalStructure(LegalEntityCreate.LegalStructure.CORPORATION)
                .metadata(
                    LegalEntityCreate.Metadata.builder()
                        .putAdditionalProperty("key", JsonValue.from("value"))
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .putAdditionalProperty("modern", JsonValue.from("treasury"))
                        .build()
                )
                .middleName("middle_name")
                .addOperatingJurisdiction("string")
                .addPhoneNumber(
                    LegalEntityCreate.PhoneNumber.builder().phoneNumber("phone_number").build()
                )
                .politicallyExposedPerson(true)
                .preferredName("preferred_name")
                .prefix("prefix")
                .addPrimarySocialMediaSite("string")
                .riskRating(LegalEntityCreate.RiskRating.LOW)
                .suffix("suffix")
                .wealthAndEmploymentDetails(
                    LegalEntityCreate.LegalEntityWealthEmploymentDetail.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .annualIncome(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .employerCountry("employer_country")
                        .employerName("employer_name")
                        .employerState("employer_state")
                        .employmentStatus(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.EmploymentStatus
                                .EMPLOYED
                        )
                        .incomeCountry("income_country")
                        .incomeSource(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.IncomeSource
                                .FAMILY_SUPPORT
                        )
                        .incomeState("income_state")
                        .industry(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.Industry.ACCOUNTING
                        )
                        .liveMode(true)
                        .object_("object")
                        .occupation(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.Occupation
                                .CONSULTING
                        )
                        .sourceOfFunds(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.SourceOfFunds
                                .ALIMONY
                        )
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .wealthSource(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.WealthSource
                                .BUSINESS_SALE
                        )
                        .build()
                )
                .website("website")
                .build()

        assertThat(legalEntityCreate.legalEntityType())
            .isEqualTo(LegalEntityCreate.LegalEntityType.BUSINESS)
        assertThat(legalEntityCreate.addresses())
            .containsExactly(
                LegalEntityAddressCreateRequest.builder()
                    .country("country")
                    .line1("line1")
                    .locality("locality")
                    .postalCode("postal_code")
                    .region("region")
                    .addAddressType(LegalEntityAddressCreateRequest.AddressType.BUSINESS)
                    .line2("line2")
                    .build()
            )
        assertThat(legalEntityCreate.bankSettings())
            .isEqualTo(
                LegalEntityCreate.LegalEntityBankSetting.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .backupWithholdingPercentage(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .enableBackupWithholding(true)
                    .liveMode(true)
                    .object_("object")
                    .privacyOptOut(true)
                    .regulationO(true)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(legalEntityCreate.businessDescription()).isEqualTo("business_description")
        assertThat(legalEntityCreate.businessName()).isEqualTo("business_name")
        assertThat(legalEntityCreate.citizenshipCountry()).isEqualTo("citizenship_country")
        assertThat(legalEntityCreate.complianceDetails())
            .isEqualTo(
                LegalEntityComplianceDetail.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .issuer("issuer")
                    .liveMode(true)
                    .object_("object")
                    .tokenExpiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .tokenIssuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .tokenUrl("token_url")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .entityValidated(true)
                    .validatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(legalEntityCreate.countryOfIncorporation()).isEqualTo("country_of_incorporation")
        assertThat(legalEntityCreate.dateFormed()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(legalEntityCreate.dateOfBirth()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(legalEntityCreate.doingBusinessAsNames()).containsExactly("string")
        assertThat(legalEntityCreate.email()).isEqualTo("email")
        assertThat(legalEntityCreate.expectedActivityVolume()).isEqualTo(0L)
        assertThat(legalEntityCreate.firstName()).isEqualTo("first_name")
        assertThat(legalEntityCreate.identifications())
            .containsExactly(
                IdentificationCreateRequest.builder()
                    .idNumber("id_number")
                    .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                    .expirationDate(LocalDate.parse("2019-12-27"))
                    .issuingCountry("issuing_country")
                    .issuingRegion("issuing_region")
                    .build()
            )
        assertThat(legalEntityCreate.industryClassifications())
            .containsExactly(
                LegalEntityIndustryClassification.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addClassificationCode("string")
                    .classificationType(LegalEntityIndustryClassification.ClassificationType.ANZSIC)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .liveMode(true)
                    .object_("object")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(legalEntityCreate.intendedUse()).isEqualTo("intended_use")
        assertThat(legalEntityCreate.lastName()).isEqualTo("last_name")
        assertThat(legalEntityCreate.legalEntityAssociations())
            .containsExactly(
                LegalEntityAssociationInlineCreate.builder()
                    .addRelationshipType(
                        LegalEntityAssociationInlineCreate.RelationshipType.AUTHORIZED_SIGNER
                    )
                    .childLegalEntity(
                        ChildLegalEntityCreate.builder()
                            .addAddress(
                                LegalEntityAddressCreateRequest.builder()
                                    .country("country")
                                    .line1("line1")
                                    .locality("locality")
                                    .postalCode("postal_code")
                                    .region("region")
                                    .addAddressType(
                                        LegalEntityAddressCreateRequest.AddressType.BUSINESS
                                    )
                                    .line2("line2")
                                    .build()
                            )
                            .bankSettings(
                                ChildLegalEntityCreate.LegalEntityBankSetting.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .backupWithholdingPercentage(0L)
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .enableBackupWithholding(true)
                                    .liveMode(true)
                                    .object_("object")
                                    .privacyOptOut(true)
                                    .regulationO(true)
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .businessDescription("business_description")
                            .businessName("business_name")
                            .citizenshipCountry("citizenship_country")
                            .complianceDetails(
                                LegalEntityComplianceDetail.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .issuer("issuer")
                                    .liveMode(true)
                                    .object_("object")
                                    .tokenExpiresAt(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .tokenIssuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .tokenUrl("token_url")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .entityValidated(true)
                                    .validatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .countryOfIncorporation("country_of_incorporation")
                            .dateFormed(LocalDate.parse("2019-12-27"))
                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                            .addDoingBusinessAsName("string")
                            .email("email")
                            .expectedActivityVolume(0L)
                            .firstName("first_name")
                            .addIdentification(
                                IdentificationCreateRequest.builder()
                                    .idNumber("id_number")
                                    .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .issuingCountry("issuing_country")
                                    .issuingRegion("issuing_region")
                                    .build()
                            )
                            .addIndustryClassification(
                                LegalEntityIndustryClassification.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addClassificationCode("string")
                                    .classificationType(
                                        LegalEntityIndustryClassification.ClassificationType.ANZSIC
                                    )
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .liveMode(true)
                                    .object_("object")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .intendedUse("intended_use")
                            .lastName("last_name")
                            .legalEntityAssociations(listOf())
                            .legalEntityType(ChildLegalEntityCreate.LegalEntityType.BUSINESS)
                            .legalStructure(ChildLegalEntityCreate.LegalStructure.CORPORATION)
                            .metadata(
                                ChildLegalEntityCreate.Metadata.builder()
                                    .putAdditionalProperty("key", JsonValue.from("value"))
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .putAdditionalProperty("modern", JsonValue.from("treasury"))
                                    .build()
                            )
                            .middleName("middle_name")
                            .addOperatingJurisdiction("string")
                            .addPhoneNumber(
                                ChildLegalEntityCreate.PhoneNumber.builder()
                                    .phoneNumber("phone_number")
                                    .build()
                            )
                            .politicallyExposedPerson(true)
                            .preferredName("preferred_name")
                            .prefix("prefix")
                            .addPrimarySocialMediaSite("string")
                            .riskRating(ChildLegalEntityCreate.RiskRating.LOW)
                            .suffix("suffix")
                            .wealthAndEmploymentDetails(
                                ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .annualIncome(0L)
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .employerCountry("employer_country")
                                    .employerName("employer_name")
                                    .employerState("employer_state")
                                    .employmentStatus(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .EmploymentStatus
                                            .EMPLOYED
                                    )
                                    .incomeCountry("income_country")
                                    .incomeSource(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .IncomeSource
                                            .FAMILY_SUPPORT
                                    )
                                    .incomeState("income_state")
                                    .industry(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .Industry
                                            .ACCOUNTING
                                    )
                                    .liveMode(true)
                                    .object_("object")
                                    .occupation(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .Occupation
                                            .CONSULTING
                                    )
                                    .sourceOfFunds(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .SourceOfFunds
                                            .ALIMONY
                                    )
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .wealthSource(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .WealthSource
                                            .BUSINESS_SALE
                                    )
                                    .build()
                            )
                            .website("website")
                            .build()
                    )
                    .childLegalEntityId("child_legal_entity_id")
                    .ownershipPercentage(0L)
                    .title("title")
                    .build()
            )
        assertThat(legalEntityCreate.legalStructure())
            .isEqualTo(LegalEntityCreate.LegalStructure.CORPORATION)
        assertThat(legalEntityCreate.metadata())
            .isEqualTo(
                LegalEntityCreate.Metadata.builder()
                    .putAdditionalProperty("key", JsonValue.from("value"))
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .putAdditionalProperty("modern", JsonValue.from("treasury"))
                    .build()
            )
        assertThat(legalEntityCreate.middleName()).isEqualTo("middle_name")
        assertThat(legalEntityCreate.operatingJurisdictions()).containsExactly("string")
        assertThat(legalEntityCreate.phoneNumbers())
            .containsExactly(
                LegalEntityCreate.PhoneNumber.builder().phoneNumber("phone_number").build()
            )
        assertThat(legalEntityCreate.politicallyExposedPerson()).isEqualTo(true)
        assertThat(legalEntityCreate.preferredName()).isEqualTo("preferred_name")
        assertThat(legalEntityCreate.prefix()).isEqualTo("prefix")
        assertThat(legalEntityCreate.primarySocialMediaSites()).containsExactly("string")
        assertThat(legalEntityCreate.riskRating()).isEqualTo(LegalEntityCreate.RiskRating.LOW)
        assertThat(legalEntityCreate.suffix()).isEqualTo("suffix")
        assertThat(legalEntityCreate.wealthAndEmploymentDetails())
            .isEqualTo(
                LegalEntityCreate.LegalEntityWealthEmploymentDetail.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .annualIncome(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .employerCountry("employer_country")
                    .employerName("employer_name")
                    .employerState("employer_state")
                    .employmentStatus(
                        LegalEntityCreate.LegalEntityWealthEmploymentDetail.EmploymentStatus
                            .EMPLOYED
                    )
                    .incomeCountry("income_country")
                    .incomeSource(
                        LegalEntityCreate.LegalEntityWealthEmploymentDetail.IncomeSource
                            .FAMILY_SUPPORT
                    )
                    .incomeState("income_state")
                    .industry(
                        LegalEntityCreate.LegalEntityWealthEmploymentDetail.Industry.ACCOUNTING
                    )
                    .liveMode(true)
                    .object_("object")
                    .occupation(
                        LegalEntityCreate.LegalEntityWealthEmploymentDetail.Occupation.CONSULTING
                    )
                    .sourceOfFunds(
                        LegalEntityCreate.LegalEntityWealthEmploymentDetail.SourceOfFunds.ALIMONY
                    )
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .wealthSource(
                        LegalEntityCreate.LegalEntityWealthEmploymentDetail.WealthSource
                            .BUSINESS_SALE
                    )
                    .build()
            )
        assertThat(legalEntityCreate.website()).isEqualTo("website")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val legalEntityCreate =
            LegalEntityCreate.builder()
                .legalEntityType(LegalEntityCreate.LegalEntityType.BUSINESS)
                .addAddress(
                    LegalEntityAddressCreateRequest.builder()
                        .country("country")
                        .line1("line1")
                        .locality("locality")
                        .postalCode("postal_code")
                        .region("region")
                        .addAddressType(LegalEntityAddressCreateRequest.AddressType.BUSINESS)
                        .line2("line2")
                        .build()
                )
                .bankSettings(
                    LegalEntityCreate.LegalEntityBankSetting.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .backupWithholdingPercentage(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .enableBackupWithholding(true)
                        .liveMode(true)
                        .object_("object")
                        .privacyOptOut(true)
                        .regulationO(true)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .businessDescription("business_description")
                .businessName("business_name")
                .citizenshipCountry("citizenship_country")
                .complianceDetails(
                    LegalEntityComplianceDetail.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .issuer("issuer")
                        .liveMode(true)
                        .object_("object")
                        .tokenExpiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .tokenIssuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .tokenUrl("token_url")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .entityValidated(true)
                        .validatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .countryOfIncorporation("country_of_incorporation")
                .dateFormed(LocalDate.parse("2019-12-27"))
                .dateOfBirth(LocalDate.parse("2019-12-27"))
                .addDoingBusinessAsName("string")
                .email("email")
                .expectedActivityVolume(0L)
                .firstName("first_name")
                .addIdentification(
                    IdentificationCreateRequest.builder()
                        .idNumber("id_number")
                        .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                        .expirationDate(LocalDate.parse("2019-12-27"))
                        .issuingCountry("issuing_country")
                        .issuingRegion("issuing_region")
                        .build()
                )
                .addIndustryClassification(
                    LegalEntityIndustryClassification.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addClassificationCode("string")
                        .classificationType(
                            LegalEntityIndustryClassification.ClassificationType.ANZSIC
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .liveMode(true)
                        .object_("object")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .intendedUse("intended_use")
                .lastName("last_name")
                .addLegalEntityAssociation(
                    LegalEntityAssociationInlineCreate.builder()
                        .addRelationshipType(
                            LegalEntityAssociationInlineCreate.RelationshipType.AUTHORIZED_SIGNER
                        )
                        .childLegalEntity(
                            ChildLegalEntityCreate.builder()
                                .addAddress(
                                    LegalEntityAddressCreateRequest.builder()
                                        .country("country")
                                        .line1("line1")
                                        .locality("locality")
                                        .postalCode("postal_code")
                                        .region("region")
                                        .addAddressType(
                                            LegalEntityAddressCreateRequest.AddressType.BUSINESS
                                        )
                                        .line2("line2")
                                        .build()
                                )
                                .bankSettings(
                                    ChildLegalEntityCreate.LegalEntityBankSetting.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .backupWithholdingPercentage(0L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .enableBackupWithholding(true)
                                        .liveMode(true)
                                        .object_("object")
                                        .privacyOptOut(true)
                                        .regulationO(true)
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .businessDescription("business_description")
                                .businessName("business_name")
                                .citizenshipCountry("citizenship_country")
                                .complianceDetails(
                                    LegalEntityComplianceDetail.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .issuer("issuer")
                                        .liveMode(true)
                                        .object_("object")
                                        .tokenExpiresAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .tokenIssuedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .tokenUrl("token_url")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .entityValidated(true)
                                        .validatedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .countryOfIncorporation("country_of_incorporation")
                                .dateFormed(LocalDate.parse("2019-12-27"))
                                .dateOfBirth(LocalDate.parse("2019-12-27"))
                                .addDoingBusinessAsName("string")
                                .email("email")
                                .expectedActivityVolume(0L)
                                .firstName("first_name")
                                .addIdentification(
                                    IdentificationCreateRequest.builder()
                                        .idNumber("id_number")
                                        .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                                        .expirationDate(LocalDate.parse("2019-12-27"))
                                        .issuingCountry("issuing_country")
                                        .issuingRegion("issuing_region")
                                        .build()
                                )
                                .addIndustryClassification(
                                    LegalEntityIndustryClassification.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .addClassificationCode("string")
                                        .classificationType(
                                            LegalEntityIndustryClassification.ClassificationType
                                                .ANZSIC
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .intendedUse("intended_use")
                                .lastName("last_name")
                                .legalEntityAssociations(listOf())
                                .legalEntityType(ChildLegalEntityCreate.LegalEntityType.BUSINESS)
                                .legalStructure(ChildLegalEntityCreate.LegalStructure.CORPORATION)
                                .metadata(
                                    ChildLegalEntityCreate.Metadata.builder()
                                        .putAdditionalProperty("key", JsonValue.from("value"))
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .putAdditionalProperty("modern", JsonValue.from("treasury"))
                                        .build()
                                )
                                .middleName("middle_name")
                                .addOperatingJurisdiction("string")
                                .addPhoneNumber(
                                    ChildLegalEntityCreate.PhoneNumber.builder()
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .politicallyExposedPerson(true)
                                .preferredName("preferred_name")
                                .prefix("prefix")
                                .addPrimarySocialMediaSite("string")
                                .riskRating(ChildLegalEntityCreate.RiskRating.LOW)
                                .suffix("suffix")
                                .wealthAndEmploymentDetails(
                                    ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                        .builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .annualIncome(0L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .employerCountry("employer_country")
                                        .employerName("employer_name")
                                        .employerState("employer_state")
                                        .employmentStatus(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .EmploymentStatus
                                                .EMPLOYED
                                        )
                                        .incomeCountry("income_country")
                                        .incomeSource(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .IncomeSource
                                                .FAMILY_SUPPORT
                                        )
                                        .incomeState("income_state")
                                        .industry(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .Industry
                                                .ACCOUNTING
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .occupation(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .Occupation
                                                .CONSULTING
                                        )
                                        .sourceOfFunds(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .SourceOfFunds
                                                .ALIMONY
                                        )
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .wealthSource(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .WealthSource
                                                .BUSINESS_SALE
                                        )
                                        .build()
                                )
                                .website("website")
                                .build()
                        )
                        .childLegalEntityId("child_legal_entity_id")
                        .ownershipPercentage(0L)
                        .title("title")
                        .build()
                )
                .legalStructure(LegalEntityCreate.LegalStructure.CORPORATION)
                .metadata(
                    LegalEntityCreate.Metadata.builder()
                        .putAdditionalProperty("key", JsonValue.from("value"))
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .putAdditionalProperty("modern", JsonValue.from("treasury"))
                        .build()
                )
                .middleName("middle_name")
                .addOperatingJurisdiction("string")
                .addPhoneNumber(
                    LegalEntityCreate.PhoneNumber.builder().phoneNumber("phone_number").build()
                )
                .politicallyExposedPerson(true)
                .preferredName("preferred_name")
                .prefix("prefix")
                .addPrimarySocialMediaSite("string")
                .riskRating(LegalEntityCreate.RiskRating.LOW)
                .suffix("suffix")
                .wealthAndEmploymentDetails(
                    LegalEntityCreate.LegalEntityWealthEmploymentDetail.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .annualIncome(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .employerCountry("employer_country")
                        .employerName("employer_name")
                        .employerState("employer_state")
                        .employmentStatus(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.EmploymentStatus
                                .EMPLOYED
                        )
                        .incomeCountry("income_country")
                        .incomeSource(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.IncomeSource
                                .FAMILY_SUPPORT
                        )
                        .incomeState("income_state")
                        .industry(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.Industry.ACCOUNTING
                        )
                        .liveMode(true)
                        .object_("object")
                        .occupation(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.Occupation
                                .CONSULTING
                        )
                        .sourceOfFunds(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.SourceOfFunds
                                .ALIMONY
                        )
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .wealthSource(
                            LegalEntityCreate.LegalEntityWealthEmploymentDetail.WealthSource
                                .BUSINESS_SALE
                        )
                        .build()
                )
                .website("website")
                .build()

        val roundtrippedLegalEntityCreate =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(legalEntityCreate),
                jacksonTypeRef<LegalEntityCreate>(),
            )

        assertThat(roundtrippedLegalEntityCreate).isEqualTo(legalEntityCreate)
    }
}
