package com.moderntreasury.api.models

import com.moderntreasury.api.models.*
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class PaymentOrderCreateParamsTest {

    @Test
    fun createPaymentOrderCreateParams() {
        PaymentOrderCreateParams.builder()
            .type(PaymentOrderType.ACH)
            .subtype(PaymentOrderSubtype.BACS_NEW_INSTRUCTION)
            .amount(123L)
            .direction(PaymentOrderCreateParams.Direction.CREDIT)
            .priority(PaymentOrderCreateParams.Priority.HIGH)
            .originatingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .receivingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .accounting(
                PaymentOrderCreateParams.Accounting.builder()
                    .accountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .classId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
            .accountingCategoryId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .accountingLedgerClassId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .currency(Currency.AED)
            .effectiveDate(LocalDate.parse("2019-12-27"))
            .description("string")
            .statementDescriptor("string")
            .remittanceInformation("string")
            .purpose("string")
            .metadata(PaymentOrderCreateParams.Metadata.builder().build())
            .chargeBearer(PaymentOrderCreateParams.ChargeBearer.SHARED)
            .foreignExchangeIndicator(
                PaymentOrderCreateParams.ForeignExchangeIndicator.FIXED_TO_VARIABLE
            )
            .foreignExchangeContract("string")
            .nsfProtected(true)
            .originatingPartyName("string")
            .ultimateOriginatingPartyName("string")
            .ultimateOriginatingPartyIdentifier("string")
            .ultimateReceivingPartyName("string")
            .ultimateReceivingPartyIdentifier("string")
            .sendRemittanceAdvice(true)
            .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
            .fallbackType(PaymentOrderCreateParams.FallbackType.ACH)
            .receivingAccount(
                PaymentOrderCreateParams.ReceivingAccount.builder()
                    .accountDetails(
                        listOf(
                            PaymentOrderCreateParams.ReceivingAccount.AccountDetail.builder()
                                .accountNumber("string")
                                .accountNumberType(
                                    PaymentOrderCreateParams.ReceivingAccount.AccountDetail
                                        .AccountNumberType
                                        .IBAN
                                )
                                .build()
                        )
                    )
                    .accountType(ExternalAccountType.CASH)
                    .contactDetails(
                        listOf(
                            PaymentOrderCreateParams.ReceivingAccount.ContactDetailCreateRequest
                                .builder()
                                .contactIdentifier("string")
                                .contactIdentifierType(
                                    PaymentOrderCreateParams.ReceivingAccount
                                        .ContactDetailCreateRequest
                                        .ContactIdentifierType
                                        .EMAIL
                                )
                                .build()
                        )
                    )
                    .ledgerAccount(
                        PaymentOrderCreateParams.ReceivingAccount.LedgerAccountCreateRequest
                            .builder()
                            .currency("string")
                            .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .normalBalance(
                                PaymentOrderCreateParams.ReceivingAccount.LedgerAccountCreateRequest
                                    .NormalBalance
                                    .CREDIT
                            )
                            .currencyExponent(123L)
                            .description("string")
                            .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .ledgerableType(
                                PaymentOrderCreateParams.ReceivingAccount.LedgerAccountCreateRequest
                                    .LedgerableType
                                    .EXTERNAL_ACCOUNT
                            )
                            .metadata(
                                PaymentOrderCreateParams.ReceivingAccount.LedgerAccountCreateRequest
                                    .Metadata
                                    .builder()
                                    .build()
                            )
                            .build()
                    )
                    .metadata(PaymentOrderCreateParams.ReceivingAccount.Metadata.builder().build())
                    .name("string")
                    .partyAddress(
                        PaymentOrderCreateParams.ReceivingAccount.AddressRequest.builder()
                            .country("string")
                            .line1("string")
                            .line2("string")
                            .locality("string")
                            .postalCode("string")
                            .region("string")
                            .build()
                    )
                    .partyIdentifier("string")
                    .partyName("string")
                    .partyType(PaymentOrderCreateParams.ReceivingAccount.PartyType.BUSINESS)
                    .plaidProcessorToken("string")
                    .routingDetails(
                        listOf(
                            PaymentOrderCreateParams.ReceivingAccount.RoutingDetail.builder()
                                .routingNumber("string")
                                .routingNumberType(
                                    PaymentOrderCreateParams.ReceivingAccount.RoutingDetail
                                        .RoutingNumberType
                                        .ABA
                                )
                                .paymentType(
                                    PaymentOrderCreateParams.ReceivingAccount.RoutingDetail
                                        .PaymentType
                                        .ACH
                                )
                                .build()
                        )
                    )
                    .build()
            )
            .ledgerTransaction(
                PaymentOrderCreateParams.LedgerTransactionCreateRequest.builder()
                    .effectiveDate(LocalDate.parse("2019-12-27"))
                    .ledgerEntries(
                        listOf(
                            PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                .LedgerEntryCreateRequest
                                .builder()
                                .amount(123L)
                                .direction(
                                    PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                        .LedgerEntryCreateRequest
                                        .Direction
                                        .CREDIT
                                )
                                .ledgerAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .availableBalanceAmount(
                                    PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                        .LedgerEntryCreateRequest
                                        .AvailableBalanceAmount
                                        .builder()
                                        .build()
                                )
                                .lockVersion(123L)
                                .pendingBalanceAmount(
                                    PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                        .LedgerEntryCreateRequest
                                        .PendingBalanceAmount
                                        .builder()
                                        .build()
                                )
                                .postedBalanceAmount(
                                    PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                        .LedgerEntryCreateRequest
                                        .PostedBalanceAmount
                                        .builder()
                                        .build()
                                )
                                .showResultingLedgerAccountBalances(true)
                                .build()
                        )
                    )
                    .description("string")
                    .externalId("string")
                    .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .ledgerableType(
                        PaymentOrderCreateParams.LedgerTransactionCreateRequest.LedgerableType
                            .COUNTERPARTY
                    )
                    .metadata(
                        PaymentOrderCreateParams.LedgerTransactionCreateRequest.Metadata.builder()
                            .build()
                    )
                    .status(PaymentOrderCreateParams.LedgerTransactionCreateRequest.Status.ARCHIVED)
                    .build()
            )
            .lineItems(
                listOf(
                    PaymentOrderCreateParams.LineItemRequest.builder()
                        .amount(123L)
                        .accountingCategoryId("string")
                        .description("string")
                        .metadata(
                            PaymentOrderCreateParams.LineItemRequest.Metadata.builder().build()
                        )
                        .build()
                )
            )
            .transactionMonitoringEnabled(true)
            .documents(
                listOf(
                    PaymentOrderCreateParams.DocumentCreateRequest.builder()
                        .file("file.txt")
                        .documentType("string")
                        .build()
                )
            )
            .build()
    }

    @Test
    fun getBody() {
        val params =
            PaymentOrderCreateParams.builder()
                .type(PaymentOrderType.ACH)
                .subtype(PaymentOrderSubtype.BACS_NEW_INSTRUCTION)
                .amount(123L)
                .direction(PaymentOrderCreateParams.Direction.CREDIT)
                .priority(PaymentOrderCreateParams.Priority.HIGH)
                .originatingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .receivingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .accounting(
                    PaymentOrderCreateParams.Accounting.builder()
                        .accountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .classId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .accountingCategoryId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .accountingLedgerClassId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .currency(Currency.AED)
                .effectiveDate(LocalDate.parse("2019-12-27"))
                .description("string")
                .statementDescriptor("string")
                .remittanceInformation("string")
                .purpose("string")
                .metadata(PaymentOrderCreateParams.Metadata.builder().build())
                .chargeBearer(PaymentOrderCreateParams.ChargeBearer.SHARED)
                .foreignExchangeIndicator(
                    PaymentOrderCreateParams.ForeignExchangeIndicator.FIXED_TO_VARIABLE
                )
                .foreignExchangeContract("string")
                .nsfProtected(true)
                .originatingPartyName("string")
                .ultimateOriginatingPartyName("string")
                .ultimateOriginatingPartyIdentifier("string")
                .ultimateReceivingPartyName("string")
                .ultimateReceivingPartyIdentifier("string")
                .sendRemittanceAdvice(true)
                .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .fallbackType(PaymentOrderCreateParams.FallbackType.ACH)
                .receivingAccount(
                    PaymentOrderCreateParams.ReceivingAccount.builder()
                        .accountDetails(
                            listOf(
                                PaymentOrderCreateParams.ReceivingAccount.AccountDetail.builder()
                                    .accountNumber("string")
                                    .accountNumberType(
                                        PaymentOrderCreateParams.ReceivingAccount.AccountDetail
                                            .AccountNumberType
                                            .IBAN
                                    )
                                    .build()
                            )
                        )
                        .accountType(ExternalAccountType.CASH)
                        .contactDetails(
                            listOf(
                                PaymentOrderCreateParams.ReceivingAccount.ContactDetailCreateRequest
                                    .builder()
                                    .contactIdentifier("string")
                                    .contactIdentifierType(
                                        PaymentOrderCreateParams.ReceivingAccount
                                            .ContactDetailCreateRequest
                                            .ContactIdentifierType
                                            .EMAIL
                                    )
                                    .build()
                            )
                        )
                        .ledgerAccount(
                            PaymentOrderCreateParams.ReceivingAccount.LedgerAccountCreateRequest
                                .builder()
                                .currency("string")
                                .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .name("string")
                                .normalBalance(
                                    PaymentOrderCreateParams.ReceivingAccount
                                        .LedgerAccountCreateRequest
                                        .NormalBalance
                                        .CREDIT
                                )
                                .currencyExponent(123L)
                                .description("string")
                                .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .ledgerableType(
                                    PaymentOrderCreateParams.ReceivingAccount
                                        .LedgerAccountCreateRequest
                                        .LedgerableType
                                        .EXTERNAL_ACCOUNT
                                )
                                .metadata(
                                    PaymentOrderCreateParams.ReceivingAccount
                                        .LedgerAccountCreateRequest
                                        .Metadata
                                        .builder()
                                        .build()
                                )
                                .build()
                        )
                        .metadata(
                            PaymentOrderCreateParams.ReceivingAccount.Metadata.builder().build()
                        )
                        .name("string")
                        .partyAddress(
                            PaymentOrderCreateParams.ReceivingAccount.AddressRequest.builder()
                                .country("string")
                                .line1("string")
                                .line2("string")
                                .locality("string")
                                .postalCode("string")
                                .region("string")
                                .build()
                        )
                        .partyIdentifier("string")
                        .partyName("string")
                        .partyType(PaymentOrderCreateParams.ReceivingAccount.PartyType.BUSINESS)
                        .plaidProcessorToken("string")
                        .routingDetails(
                            listOf(
                                PaymentOrderCreateParams.ReceivingAccount.RoutingDetail.builder()
                                    .routingNumber("string")
                                    .routingNumberType(
                                        PaymentOrderCreateParams.ReceivingAccount.RoutingDetail
                                            .RoutingNumberType
                                            .ABA
                                    )
                                    .paymentType(
                                        PaymentOrderCreateParams.ReceivingAccount.RoutingDetail
                                            .PaymentType
                                            .ACH
                                    )
                                    .build()
                            )
                        )
                        .build()
                )
                .ledgerTransaction(
                    PaymentOrderCreateParams.LedgerTransactionCreateRequest.builder()
                        .effectiveDate(LocalDate.parse("2019-12-27"))
                        .ledgerEntries(
                            listOf(
                                PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                    .LedgerEntryCreateRequest
                                    .builder()
                                    .amount(123L)
                                    .direction(
                                        PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                            .LedgerEntryCreateRequest
                                            .Direction
                                            .CREDIT
                                    )
                                    .ledgerAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .availableBalanceAmount(
                                        PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                            .LedgerEntryCreateRequest
                                            .AvailableBalanceAmount
                                            .builder()
                                            .build()
                                    )
                                    .lockVersion(123L)
                                    .pendingBalanceAmount(
                                        PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                            .LedgerEntryCreateRequest
                                            .PendingBalanceAmount
                                            .builder()
                                            .build()
                                    )
                                    .postedBalanceAmount(
                                        PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                            .LedgerEntryCreateRequest
                                            .PostedBalanceAmount
                                            .builder()
                                            .build()
                                    )
                                    .showResultingLedgerAccountBalances(true)
                                    .build()
                            )
                        )
                        .description("string")
                        .externalId("string")
                        .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .ledgerableType(
                            PaymentOrderCreateParams.LedgerTransactionCreateRequest.LedgerableType
                                .COUNTERPARTY
                        )
                        .metadata(
                            PaymentOrderCreateParams.LedgerTransactionCreateRequest.Metadata
                                .builder()
                                .build()
                        )
                        .status(
                            PaymentOrderCreateParams.LedgerTransactionCreateRequest.Status.ARCHIVED
                        )
                        .build()
                )
                .lineItems(
                    listOf(
                        PaymentOrderCreateParams.LineItemRequest.builder()
                            .amount(123L)
                            .accountingCategoryId("string")
                            .description("string")
                            .metadata(
                                PaymentOrderCreateParams.LineItemRequest.Metadata.builder().build()
                            )
                            .build()
                    )
                )
                .transactionMonitoringEnabled(true)
                .documents(
                    listOf(
                        PaymentOrderCreateParams.DocumentCreateRequest.builder()
                            .file("file.txt")
                            .documentType("string")
                            .build()
                    )
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.type()).isEqualTo(PaymentOrderType.ACH)
        assertThat(body.subtype()).isEqualTo(PaymentOrderSubtype.BACS_NEW_INSTRUCTION)
        assertThat(body.amount()).isEqualTo(123L)
        assertThat(body.direction()).isEqualTo(PaymentOrderCreateParams.Direction.CREDIT)
        assertThat(body.priority()).isEqualTo(PaymentOrderCreateParams.Priority.HIGH)
        assertThat(body.originatingAccountId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.receivingAccountId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.accounting())
            .isEqualTo(
                PaymentOrderCreateParams.Accounting.builder()
                    .accountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .classId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
        assertThat(body.accountingCategoryId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.accountingLedgerClassId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(body.currency()).isEqualTo(Currency.AED)
        assertThat(body.effectiveDate()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(body.description()).isEqualTo("string")
        assertThat(body.statementDescriptor()).isEqualTo("string")
        assertThat(body.remittanceInformation()).isEqualTo("string")
        assertThat(body.purpose()).isEqualTo("string")
        assertThat(body.metadata()).isEqualTo(PaymentOrderCreateParams.Metadata.builder().build())
        assertThat(body.chargeBearer()).isEqualTo(PaymentOrderCreateParams.ChargeBearer.SHARED)
        assertThat(body.foreignExchangeIndicator())
            .isEqualTo(PaymentOrderCreateParams.ForeignExchangeIndicator.FIXED_TO_VARIABLE)
        assertThat(body.foreignExchangeContract()).isEqualTo("string")
        assertThat(body.nsfProtected()).isEqualTo(true)
        assertThat(body.originatingPartyName()).isEqualTo("string")
        assertThat(body.ultimateOriginatingPartyName()).isEqualTo("string")
        assertThat(body.ultimateOriginatingPartyIdentifier()).isEqualTo("string")
        assertThat(body.ultimateReceivingPartyName()).isEqualTo("string")
        assertThat(body.ultimateReceivingPartyIdentifier()).isEqualTo("string")
        assertThat(body.sendRemittanceAdvice()).isEqualTo(true)
        assertThat(body.expiresAt()).isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(body.fallbackType()).isEqualTo(PaymentOrderCreateParams.FallbackType.ACH)
        assertThat(body.receivingAccount())
            .isEqualTo(
                PaymentOrderCreateParams.ReceivingAccount.builder()
                    .accountDetails(
                        listOf(
                            PaymentOrderCreateParams.ReceivingAccount.AccountDetail.builder()
                                .accountNumber("string")
                                .accountNumberType(
                                    PaymentOrderCreateParams.ReceivingAccount.AccountDetail
                                        .AccountNumberType
                                        .IBAN
                                )
                                .build()
                        )
                    )
                    .accountType(ExternalAccountType.CASH)
                    .contactDetails(
                        listOf(
                            PaymentOrderCreateParams.ReceivingAccount.ContactDetailCreateRequest
                                .builder()
                                .contactIdentifier("string")
                                .contactIdentifierType(
                                    PaymentOrderCreateParams.ReceivingAccount
                                        .ContactDetailCreateRequest
                                        .ContactIdentifierType
                                        .EMAIL
                                )
                                .build()
                        )
                    )
                    .ledgerAccount(
                        PaymentOrderCreateParams.ReceivingAccount.LedgerAccountCreateRequest
                            .builder()
                            .currency("string")
                            .ledgerId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .name("string")
                            .normalBalance(
                                PaymentOrderCreateParams.ReceivingAccount.LedgerAccountCreateRequest
                                    .NormalBalance
                                    .CREDIT
                            )
                            .currencyExponent(123L)
                            .description("string")
                            .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .ledgerableType(
                                PaymentOrderCreateParams.ReceivingAccount.LedgerAccountCreateRequest
                                    .LedgerableType
                                    .EXTERNAL_ACCOUNT
                            )
                            .metadata(
                                PaymentOrderCreateParams.ReceivingAccount.LedgerAccountCreateRequest
                                    .Metadata
                                    .builder()
                                    .build()
                            )
                            .build()
                    )
                    .metadata(PaymentOrderCreateParams.ReceivingAccount.Metadata.builder().build())
                    .name("string")
                    .partyAddress(
                        PaymentOrderCreateParams.ReceivingAccount.AddressRequest.builder()
                            .country("string")
                            .line1("string")
                            .line2("string")
                            .locality("string")
                            .postalCode("string")
                            .region("string")
                            .build()
                    )
                    .partyIdentifier("string")
                    .partyName("string")
                    .partyType(PaymentOrderCreateParams.ReceivingAccount.PartyType.BUSINESS)
                    .plaidProcessorToken("string")
                    .routingDetails(
                        listOf(
                            PaymentOrderCreateParams.ReceivingAccount.RoutingDetail.builder()
                                .routingNumber("string")
                                .routingNumberType(
                                    PaymentOrderCreateParams.ReceivingAccount.RoutingDetail
                                        .RoutingNumberType
                                        .ABA
                                )
                                .paymentType(
                                    PaymentOrderCreateParams.ReceivingAccount.RoutingDetail
                                        .PaymentType
                                        .ACH
                                )
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(body.ledgerTransaction())
            .isEqualTo(
                PaymentOrderCreateParams.LedgerTransactionCreateRequest.builder()
                    .effectiveDate(LocalDate.parse("2019-12-27"))
                    .ledgerEntries(
                        listOf(
                            PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                .LedgerEntryCreateRequest
                                .builder()
                                .amount(123L)
                                .direction(
                                    PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                        .LedgerEntryCreateRequest
                                        .Direction
                                        .CREDIT
                                )
                                .ledgerAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .availableBalanceAmount(
                                    PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                        .LedgerEntryCreateRequest
                                        .AvailableBalanceAmount
                                        .builder()
                                        .build()
                                )
                                .lockVersion(123L)
                                .pendingBalanceAmount(
                                    PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                        .LedgerEntryCreateRequest
                                        .PendingBalanceAmount
                                        .builder()
                                        .build()
                                )
                                .postedBalanceAmount(
                                    PaymentOrderCreateParams.LedgerTransactionCreateRequest
                                        .LedgerEntryCreateRequest
                                        .PostedBalanceAmount
                                        .builder()
                                        .build()
                                )
                                .showResultingLedgerAccountBalances(true)
                                .build()
                        )
                    )
                    .description("string")
                    .externalId("string")
                    .ledgerableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .ledgerableType(
                        PaymentOrderCreateParams.LedgerTransactionCreateRequest.LedgerableType
                            .COUNTERPARTY
                    )
                    .metadata(
                        PaymentOrderCreateParams.LedgerTransactionCreateRequest.Metadata.builder()
                            .build()
                    )
                    .status(PaymentOrderCreateParams.LedgerTransactionCreateRequest.Status.ARCHIVED)
                    .build()
            )
        assertThat(body.lineItems())
            .isEqualTo(
                listOf(
                    PaymentOrderCreateParams.LineItemRequest.builder()
                        .amount(123L)
                        .accountingCategoryId("string")
                        .description("string")
                        .metadata(
                            PaymentOrderCreateParams.LineItemRequest.Metadata.builder().build()
                        )
                        .build()
                )
            )
        assertThat(body.transactionMonitoringEnabled()).isEqualTo(true)
        assertThat(body.documents())
            .isEqualTo(
                listOf(
                    PaymentOrderCreateParams.DocumentCreateRequest.builder()
                        .file("file.txt")
                        .documentType("string")
                        .build()
                )
            )
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            PaymentOrderCreateParams.builder()
                .type(PaymentOrderType.ACH)
                .amount(123L)
                .direction(PaymentOrderCreateParams.Direction.CREDIT)
                .originatingAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.type()).isEqualTo(PaymentOrderType.ACH)
        assertThat(body.amount()).isEqualTo(123L)
        assertThat(body.direction()).isEqualTo(PaymentOrderCreateParams.Direction.CREDIT)
        assertThat(body.originatingAccountId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
    }
}
